// react-ussd/src/components/UssdSession.jsx
import React, { useEffect, useRef, useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "./UssdSession.css"; // Optional for custom tweaks

// Mock service (to be replaced with your actual backend service)
import { UssdService } from "../services/UssdService";

function UssdSession() {
  const [ussdContent, setUssdContent] = useState("");
  const [showInput, setShowInput] = useState(false);
  const [showEnd, setShowEnd] = useState(false);
  const [loading, setLoading] = useState(false);
  const [inputText, setInputText] = useState("");
  const inputRef = useRef(null);

  const sessionKey = "ussd_session_id";
  const ussd = new UssdService();

  const getSessionId = () => {
    let sessionId = sessionStorage.getItem(sessionKey);
    if (!sessionId) {
      sessionId = ussd.generateSessionId();
      sessionStorage.setItem(sessionKey, sessionId);
    }
    return sessionId;
  };

  const clearSession = () => {
    sessionStorage.removeItem(sessionKey);
  };

  const sendUSSD = async (text = "") => {
    const sessionId = getSessionId();
    const phoneNumber = ussd.getPhoneNumber();
    const appCode = ussd.getSelectedApp()?.code;

    setLoading(true);
    try {
      const response = await ussd.sendUSSD({ text, phoneNumber, sessionId, appCode });
      setLoading(false);

      const respType = response.slice(0, 3).toLowerCase();
      const content = response.slice(3).trim();
      setUssdContent(content);

      if (respType === "con") {
        setShowInput(true);
        setShowEnd(false);
        setTimeout(() => inputRef.current?.focus(), 100);
      } else {
        setShowInput(false);
        setShowEnd(true);
        clearSession();
      }
    } catch (err) {
      setLoading(false);
      alert("USSD request failed");
    }
  };

  const startSession = () => {
    setUssdContent("");
    setShowInput(false);
    setShowEnd(false);
    sendUSSD("");
  };

  const submitInput = () => {
    if (!inputText.trim()) return;
    sendUSSD(inputText.trim());
    setInputText("");
  };

  const cancelSession = () => {
    setShowInput(false);
    setShowEnd(false);
    setUssdContent("");
    setInputText("");
    clearSession();
  };

  useEffect(() => {
    if (showInput && inputRef.current) {
      inputRef.current.focus();
    }
  }, [showInput]);

  return (
    <div className="container-fullscreen bg-white rounded shadow-sm ussd-container d-flex flex-column">
      {/* Body */}
      <div className="ussd-body flex-grow-1 d-flex justify-content-center align-items-center text-center w-100 px-3">
        {loading && (
          <div className="loader">
            <div className="spinner-border text-primary" role="status"></div>
          </div>
        )}

        {!loading && ussdContent && (
          <div className="ussd-content w-100">
            <pre>{ussdContent}</pre>
          </div>
        )}

        {!loading && !ussdContent && !showInput && (
          <div id="start-section">
            <button className="btn btn-primary btn-lg" onClick={startSession}>
              Start USSD
            </button>
          </div>
        )}
      </div>

      {/* Footer input controls */}
      {showInput && (
        <div className="ussd-footer bg-white border-top p-2 w-100">
          <div className="d-flex w-100 gap-2 mb-0">
            <input
              ref={inputRef}
              type="text"
              className="form-control"
              placeholder="Enter option..."
              autoComplete="off"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
            />
            <button type="button" className="btn btn-primary" onClick={submitInput}>
              <i className="bi bi-send"></i>
            </button>
            <button type="button" className="btn btn-outline-secondary" onClick={cancelSession}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {/* Footer for END message */}
      {showEnd && (
        <div className="ussd-footer bg-white border-top p-3 text-center w-100">
          <button className="btn btn-secondary w-50" onClick={cancelSession}>
            Dismiss
          </button>
        </div>
      )}
    </div>
  );
}

export default UssdSession;

// angular-ussd/src/app/pages/ussd-session/ussd-session.component.ts
import { Component, OnInit, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
import { ToastService } from 'src/app/services/toast-service';
import { UssdService } from 'src/app/services/ussd-service';

@Component({
  selector: 'app-ussd-session',
  templateUrl: './ussd-session.component.html',
  styleUrls: ['./ussd-session.component.scss']
})
export class UssdSessionComponent implements OnInit, AfterViewInit {
  ussdForm!: FormGroup;
  ussdContent = '';
  showInput = false;
  showEnd = false;
  loading = false;

  selectedAppName = ''; // ✅ add this line
  private sessionKey = 'ussd_session_id';

  @ViewChild('inputField') inputField!: ElementRef;

  constructor(
    private fb: FormBuilder,
    private ussd: UssdService,
    private toast: ToastService
  ) {}

  ngOnInit() {
    this.ussdForm = this.fb.group({
      inputText: ['']
    });

    this.selectedAppName = this.ussd.getSelectedApp();
  }

  ngAfterViewInit() {
    if (this.inputField) {
      this.inputField.nativeElement.focus();
    }
  }

  private getSessionId(): string {
    let sessionId = sessionStorage.getItem(this.sessionKey);
    if (!sessionId) {
      sessionId = this.ussd.generateSessionId();
      sessionStorage.setItem(this.sessionKey, sessionId);
    }
    return sessionId;
  }

  private clearSession() {
    sessionStorage.removeItem(this.sessionKey);
  }

  startSession() {
    this.ussdContent = '';
    this.showInput = false;
    this.showEnd = false;
    this.sendUSSD('');
  }

  sendUSSD(text: string) {
    const phoneNumber = this.ussd.getPhoneNumber() || '';
    // console.log(this.ussd.getSelectedApp());
    const appCode = this.ussd.getSelectedApp().code;
    const sessionId = this.getSessionId();

    this.loading = true;

    this.ussd.sendUSSD({ text, phoneNumber, sessionId, appCode }).subscribe({
      next: (response: string) => {
        this.loading = false;
        const respType = response.slice(0, 3).toLowerCase();
        this.ussdContent = response.slice(3).trim();

        if (respType === 'con') {
          this.showInput = true;
          this.showEnd = false;
          setTimeout(() => this.inputField?.nativeElement.focus(), 100);
        } else {
          this.showInput = false;
          this.showEnd = true;
          this.clearSession();
        }
      },
      error: () => {
        this.loading = false;
        this.toast.show('USSD request failed', 'danger');
      }
    });
  }

  submitInput() {
    const text = this.ussdForm.get('inputText')?.value?.trim() || '';
    if (!text) return;
    this.sendUSSD(text);
    this.ussdForm.reset();
  }

  cancelSession() {
    this.showInput = false;
    this.showEnd = false;
    this.ussdContent = '';
    this.ussdForm.reset();
    this.clearSession();
  }
}

<div class="container-fullscreen bg-white border rounded shadow-sm ussd-container">
  <!-- Header -->
  <!-- <div class="bg-primary text-white text-center py-2 rounded-top w-100">
    <h5 class="mb-0">USSD Session</h5>
    <small *ngIf="selectedAppName">App: {{ selectedAppName }}</small>
    <small *ngIf="!selectedAppName">No app selected</small>
  </div> -->

  <!-- Body -->
  <div class="ussd-body flex-grow-1 d-flex justify-content-center align-items-center text-center w-100 px-3">
    <div *ngIf="loading" class="loader">
      <div class="spinner-border text-primary" role="status"></div>
    </div>

    <div *ngIf="ussdContent && !loading" class="ussd-content w-100">
      <pre>{{ ussdContent }}</pre>
    </div>

    <div *ngIf="!showInput && !ussdContent && !loading" id="start-section">
      <button class="btn btn-primary btn-lg" (click)="startSession()">Start USSD</button>
    </div>
  </div>

  <!-- Footer input controls -->
  <div class="ussd-footer bg-white border-top p-2 w-100" *ngIf="showInput">
    <form [formGroup]="ussdForm" class="d-flex w-100 gap-2 mb-0">
      <input #inputField type="text" formControlName="inputText" class="form-control" placeholder="Enter option..." autocomplete="off">
      <button type="button" class="btn btn-primary" (click)="submitInput()">
        <i class="bi bi-send"></i>
      </button>
      <button type="button" class="btn btn-outline-secondary" (click)="cancelSession()">Cancel</button>
    </form>
  </div>

  <!-- Footer for END message -->
  <div class="ussd-footer bg-white border-top p-3 text-center w-100" *ngIf="showEnd">
    <button class="btn btn-secondary w-50" (click)="cancelSession()">Dismiss</button>
  </div>
</div>
