// react-ussd/src/components/NavBar.jsx
import React, { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./NavBar.css";
import { UssdService } from "../services/UssdService";

function Navbar() {
  const [selectedAppName, setSelectedAppName] = useState("");
  const location = useLocation();
  const ussd = new UssdService();

  // Mimic Angular's BehaviorSubject-like subscription
  useEffect(() => {
    const app = ussd.getSelectedApp();
    setSelectedAppName(app?.name || "None");
  }, [location]); // update when route changes

  return (
    <nav className="navbar navbar-expand-lg navbar-dark py-2 px-3 shadow-sm">
      <div className="container-fluid flex-column align-items-center">
        {/* Top row: buttons */}
        <div className="d-flex justify-content-around w-100 mb-2">
          <Link to="/session" className="btn btn-outline-light btn-sm btn-navbar">
            <i className="bi bi-telephone"></i> Session
          </Link>
          <Link to="/add-app" className="btn btn-outline-light btn-sm btn-navbar">
            <i className="bi bi-plus-circle"></i> Add App
          </Link>
          <Link to="/settings" className="btn btn-outline-light btn-sm btn-navbar">
            <i className="bi bi-gear"></i> Settings
          </Link>
        </div>

        {/* Bottom row: active app name */}
        <div className="navbar-center text-light text-center">
          <span className="fw-semibold">Active App:</span>
          <span className="text-warning ms-1">
            {selectedAppName || "None"}
          </span>
        </div>
      </div>
    </nav>
  );
}

export default Navbar;

// angular-ussd/src/app/shared/navbar/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Subscription } from 'rxjs';
import { UssdService } from 'src/app/services/ussd-service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
selectedAppName = '';
  private sub!: Subscription;

  constructor(private ussd: UssdService) {}

  ngOnInit() {
    this.sub = this.ussd.selectedApp$.subscribe(
      app => {
        this.selectedAppName = app.name;
      }
    );
  }

  ngOnDestroy() {
    if (this.sub) this.sub.unsubscribe();
  }
}

<nav class="navbar navbar-expand-lg navbar-dark py-2 px-3 shadow-sm">
  <div class="container-fluid flex-column align-items-center">
    <!-- Top row: navigation buttons -->
    <div class="d-flex justify-content-around w-100 mb-2">
      <a routerLink="/session" class="btn btn-outline-light btn-sm btn-navbar">
        <i class="bi bi-telephone"></i> Session
      </a>
      <!-- <a routerLink="/add-app" class="btn btn-outline-light btn-sm btn-navbar">
        <i class="bi bi-plus-circle"></i> Add App
      </a> -->
      <a routerLink="/settings" class="btn btn-outline-light btn-sm btn-navbar">
        <i class="bi bi-gear"></i> Settings
      </a>
    </div>

    <!-- Bottom row: active app name -->
    <div class="navbar-center text-light text-center">
      <span class="fw-semibold">Active App:</span>
      <span class="text-warning ms-1">{{ selectedAppName || 'None' }}</span>
    </div>
  </div>
</nav>
